// ═══ EQUIPMENT DATABASE — 150+ Equipment Items ═══

import type { EquipmentItem } from './types'

export const EQUIPMENT_DATABASE: EquipmentItem[] = [
  // ═══ VIDÉOSURVEILLANCE — CAMÉRAS DÔME ═══
  { id: 'eq-001', brand: 'Wisenet', model: 'XNV-8080R', category: 'camera_dome', subcategory: 'Dôme intérieur 5MP', specs: { resolution: '5MP', fov: 109, rangeM: 12, ip_rating: 'IP52', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 15, sensor_size: '1/2.8"' }, price_fcfa: 850_000, price_eur: 1295, datasheet_url: '', certifications: ['CE', 'EN 62676', 'FCC'], compatible_with: ['Wisenet WAVE', 'XRN-3210'], installation_notes: 'Montage plafond. Hauteur recommandée 3-4m.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-002', brand: 'Wisenet', model: 'QNV-8080R', category: 'camera_dome', subcategory: 'Dôme vandal-proof 5MP', specs: { resolution: '5MP', fov: 109, rangeM: 10, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 20 }, price_fcfa: 920_000, price_eur: 1402, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IK10'], compatible_with: ['Wisenet WAVE', 'XRN-3210'], installation_notes: 'Anti-vandale. Zones techniques et parking.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-003', brand: 'Wisenet', model: 'XND-8080RV', category: 'camera_dome', subcategory: 'Dôme IR 5MP', specs: { resolution: '5MP', fov: 104, rangeM: 12, ip_rating: 'IP52', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 780_000, price_eur: 1189, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE'], installation_notes: 'IR longue portée. Idéal couloirs.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-004', brand: 'Wisenet', model: 'QND-8080R', category: 'camera_dome', subcategory: 'Dôme compact 5MP', specs: { resolution: '5MP', fov: 109, rangeM: 10, ip_rating: 'IP52', power_watts: 9, poe: true, h265: true, wdr: true, ir_range_m: 15 }, price_fcfa: 680_000, price_eur: 1036, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Compact. Boutiques et commerces.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-005', brand: 'Axis', model: 'P3245-V', category: 'camera_dome', subcategory: 'Dôme fixe 2MP', specs: { resolution: '2MP', fov: 109, rangeM: 10, ip_rating: 'IP52', ik_rating: 'IK08', power_watts: 13, poe: true, h265: true, wdr: true, ir_range_m: 15 }, price_fcfa: 750_000, price_eur: 1143, datasheet_url: '', certifications: ['CE', 'ONVIF Profile S/G/T'], compatible_with: ['Axis Camera Station', 'Milestone'], installation_notes: 'Lightfinder 2.0. Excellent en faible luminosité.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-006', brand: 'Axis', model: 'M3106-L', category: 'camera_dome', subcategory: 'Dôme mini 4MP', specs: { resolution: '4MP', fov: 130, rangeM: 8, ip_rating: 'IP42', power_watts: 5, poe: true, h265: true, wdr: false, ir_range_m: 15 }, price_fcfa: 420_000, price_eur: 640, datasheet_url: '', certifications: ['CE', 'ONVIF'], compatible_with: ['Axis Camera Station'], installation_notes: 'Mini dôme discret. Petits espaces.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-007', brand: 'Axis', model: 'M3116-LVE', category: 'camera_dome', subcategory: 'Dôme extérieur 4MP', specs: { resolution: '4MP', fov: 105, rangeM: 10, ip_rating: 'IP66', ik_rating: 'IK08', power_watts: 7, poe: true, h265: true, wdr: true, ir_range_m: 20 }, price_fcfa: 580_000, price_eur: 884, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66'], compatible_with: ['Axis Camera Station', 'Milestone'], installation_notes: 'Extérieur. Entrées et périmètre.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-008', brand: 'Bosch', model: 'FLEXIDOME IP 7000i', category: 'camera_dome', subcategory: 'Dôme intelligent 2MP', specs: { resolution: '2MP', fov: 117, rangeM: 12, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 18, poe: true, h265: true, wdr: true, ir_range_m: 25 }, price_fcfa: 980_000, price_eur: 1493, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IK10', 'IP66'], compatible_with: ['Bosch VMS', 'BVMS'], installation_notes: 'Analytique intégrée. Détection intrusion.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-009', brand: 'Hikvision', model: 'DS-2CD2387G2', category: 'camera_dome', subcategory: 'Dôme 8MP (4K)', specs: { resolution: '8MP', fov: 102, rangeM: 10, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 520_000, price_eur: 793, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Hikvision iVMS', 'HikCentral'], installation_notes: 'Budget 4K. Rapport qualité/prix excellent.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-010', brand: 'Hikvision', model: 'DS-2CD2H83G2', category: 'camera_dome', subcategory: 'Dôme turret 8MP', specs: { resolution: '8MP', fov: 108, rangeM: 12, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 480_000, price_eur: 732, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Hikvision iVMS'], installation_notes: 'Turret 4K. Galeries commerciales.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-011', brand: 'Dahua', model: 'IPC-HDW3849H', category: 'camera_dome', subcategory: 'Dôme eye-ball 8MP', specs: { resolution: '8MP', fov: 102, rangeM: 10, ip_rating: 'IP67', ik_rating: 'IK10', power_watts: 10, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 580_000, price_eur: 884, datasheet_url: '', certifications: ['CE', 'IK10'], compatible_with: ['Dahua DSS', 'SmartPSS'], installation_notes: 'Eye-ball orientable. Zones commerciales.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-012', brand: 'Panasonic', model: 'WV-S2136', category: 'camera_dome', subcategory: 'Dôme AI 2MP', specs: { resolution: '2MP', fov: 104, rangeM: 12, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 14, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 890_000, price_eur: 1356, datasheet_url: '', certifications: ['CE', 'IP66', 'IK10'], compatible_with: ['Panasonic i-PRO'], installation_notes: 'IA embarquée. Détection de personnes.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ CAMÉRAS PTZ ═══
  { id: 'eq-013', brand: 'Wisenet', model: 'QNP-9300RWB', category: 'camera_ptz', subcategory: 'PTZ extérieur 4K', specs: { resolution: '4K', fov: 120, rangeM: 30, ip_rating: 'IP66', power_watts: 60, poe: false, h265: true, wdr: true, ir_range_m: 100 }, price_fcfa: 2_800_000, price_eur: 4268, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Poteau ou mât. Alimentation 24VAC.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-014', brand: 'Wisenet', model: 'XNP-9300RW', category: 'camera_ptz', subcategory: 'PTZ premium 4K', specs: { resolution: '4K', fov: 120, rangeM: 50, ip_rating: 'IP66', power_watts: 65, poe: false, h265: true, wdr: true, ir_range_m: 150 }, price_fcfa: 3_200_000, price_eur: 4878, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'IR 150m. Parking et périmètre.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-015', brand: 'Wisenet', model: 'PTZ-P3', category: 'camera_ptz', subcategory: 'PTZ panoramique 4K', specs: { resolution: '4K', fov: 360, rangeM: 50, ip_rating: 'IP66', power_watts: 70, poe: false, h265: true, wdr: true, ir_range_m: 100 }, price_fcfa: 3_500_000, price_eur: 5335, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Couverture 360°. Zones centrales.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-016', brand: 'Axis', model: 'P5676-LE', category: 'camera_ptz', subcategory: 'PTZ 4MP OptimizedIR', specs: { resolution: '4MP', fov: 120, rangeM: 40, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 55, poe: false, h265: true, wdr: true, ir_range_m: 150 }, price_fcfa: 3_100_000, price_eur: 4726, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66', 'IK10'], compatible_with: ['Axis Camera Station', 'Milestone'], installation_notes: 'OptimizedIR. Extérieur longue portée.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-017', brand: 'Axis', model: 'Q6135-LE', category: 'camera_ptz', subcategory: 'PTZ 2MP HDTV', specs: { resolution: '2MP', fov: 120, rangeM: 30, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 50, poe: false, h265: true, wdr: true, ir_range_m: 200 }, price_fcfa: 4_200_000, price_eur: 6403, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66'], compatible_with: ['Axis Camera Station'], installation_notes: 'IR 200m. Périmètre grande distance.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-018', brand: 'Hikvision', model: 'DS-2DE4425IW', category: 'camera_ptz', subcategory: 'PTZ 4MP 25x', specs: { resolution: '4MP', fov: 120, rangeM: 35, ip_rating: 'IP66', power_watts: 30, poe: true, h265: true, wdr: true, ir_range_m: 100 }, price_fcfa: 1_200_000, price_eur: 1829, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Hikvision iVMS'], installation_notes: 'PTZ PoE abordable. Parking intérieur.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-019', brand: 'Bosch', model: 'AUTODOME IP 5000i', category: 'camera_ptz', subcategory: 'PTZ intelligent 2MP', specs: { resolution: '2MP', fov: 120, rangeM: 30, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 50, poe: false, h265: true, wdr: true, ir_range_m: 120 }, price_fcfa: 3_800_000, price_eur: 5793, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66', 'IK10'], compatible_with: ['Bosch VMS'], installation_notes: 'Tracking intelligent. Analytique embarquée.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ CAMÉRAS BULLET ═══
  { id: 'eq-020', brand: 'Wisenet', model: 'QNO-8080R', category: 'camera_bullet', subcategory: 'Bullet extérieur 5MP', specs: { resolution: '5MP', fov: 90, rangeM: 14, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 25 }, price_fcfa: 780_000, price_eur: 1189, datasheet_url: '', certifications: ['CE', 'IP66', 'IK10'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Couloirs et sorties. Montage mural.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-021', brand: 'Wisenet', model: 'XNV-6120', category: 'camera_bullet', subcategory: 'Bullet 2MP IR', specs: { resolution: '2MP', fov: 94, rangeM: 12, ip_rating: 'IP66', power_watts: 10, poe: true, h265: true, wdr: true, ir_range_m: 50 }, price_fcfa: 650_000, price_eur: 991, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'IR longue portée. Allées extérieures.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-022', brand: 'Axis', model: 'P1448-LE', category: 'camera_bullet', subcategory: 'Bullet 4K', specs: { resolution: '8MP', fov: 100, rangeM: 15, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 15, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 1_100_000, price_eur: 1677, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66'], compatible_with: ['Axis Camera Station'], installation_notes: '4K bullet extérieur. Entrées principales.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-023', brand: 'Hikvision', model: 'DS-2CD2T47G2', category: 'camera_bullet', subcategory: 'Bullet 4MP AcuSense', specs: { resolution: '4MP', fov: 86, rangeM: 16, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 60 }, price_fcfa: 620_000, price_eur: 945, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Hikvision iVMS', 'HikCentral'], installation_notes: 'AcuSense. Détection personne/véhicule.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-024', brand: 'Dahua', model: 'IPC-HFW2849T', category: 'camera_bullet', subcategory: 'Bullet 8MP WizSense', specs: { resolution: '8MP', fov: 102, rangeM: 12, ip_rating: 'IP67', power_watts: 11, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 480_000, price_eur: 732, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Dahua DSS'], installation_notes: '4K budget. Périmètre extérieur.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-025', brand: 'Bosch', model: 'DINION IP 5000', category: 'camera_bullet', subcategory: 'Bullet 5MP Starlight', specs: { resolution: '5MP', fov: 96, rangeM: 15, ip_rating: 'IP66', power_watts: 14, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 920_000, price_eur: 1402, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Bosch VMS'], installation_notes: 'Starlight. Performance nocturne.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ CAMÉRAS MULTIDIRECTIONNELLES ═══
  { id: 'eq-026', brand: 'Wisenet', model: 'PNM-9000VQ', category: 'camera_multidirectional', subcategory: 'Multi 4x2MP', specs: { resolution: '4x2MP', fov: 270, rangeM: 8, ip_rating: 'IP52', power_watts: 25, poe: true, h265: true, wdr: true, ir_range_m: 15 }, price_fcfa: 1_280_000, price_eur: 1951, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Plafond zones larges. Remplace 3-4 dômes.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-027', brand: 'Wisenet', model: 'PNM-9000QB', category: 'camera_multidirectional', subcategory: 'Multi 4x5MP', specs: { resolution: '4x5MP', fov: 280, rangeM: 10, ip_rating: 'IP52', power_watts: 30, poe: true, h265: true, wdr: true, ir_range_m: 15 }, price_fcfa: 1_650_000, price_eur: 2515, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Multi 5MP. Food court et grands espaces.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-028', brand: 'Axis', model: 'M4308-PLE', category: 'camera_multidirectional', subcategory: 'Panoramique 12MP', specs: { resolution: '12MP', fov: 360, rangeM: 8, ip_rating: 'IP66', power_watts: 25, poe: true, h265: true, wdr: true, ir_range_m: 15 }, price_fcfa: 2_200_000, price_eur: 3354, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66'], compatible_with: ['Axis Camera Station'], installation_notes: 'Panoramique 360°. Atriums.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-029', brand: 'Dahua', model: 'IPC-PDBW8802', category: 'camera_multidirectional', subcategory: 'Multi 4x2MP + PTZ', specs: { resolution: '4x2MP', fov: 360, rangeM: 10, ip_rating: 'IP67', power_watts: 35, poe: false, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Dahua DSS'], installation_notes: 'Multi + PTZ intégré. Zones critiques.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-030', brand: 'Wisenet', model: 'PNV-A9081R', category: 'camera_multidirectional', subcategory: 'AI Multi 4K', specs: { resolution: '4x8MP', fov: 300, rangeM: 12, ip_rating: 'IP66', power_watts: 35, poe: true, h265: true, wdr: true, ir_range_m: 20 }, price_fcfa: 2_500_000, price_eur: 3811, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Multi AI. Analytique avancée.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },

  // ═══ CAMÉRAS FISHEYE ═══
  { id: 'eq-031', brand: 'Wisenet', model: 'XNF-9300RV', category: 'camera_fisheye', subcategory: 'Fisheye 360° 12MP', specs: { resolution: '12MP', fov: 360, rangeM: 6, ip_rating: 'IP52', power_watts: 15, poe: true, h265: true, wdr: true, ir_range_m: 10 }, price_fcfa: 1_150_000, price_eur: 1753, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Plafond. Dewarping multi-vues.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-032', brand: 'Axis', model: 'M3077-PLVE', category: 'camera_fisheye', subcategory: 'Fisheye 360° 6MP', specs: { resolution: '6MP', fov: 360, rangeM: 5, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 10 }, price_fcfa: 1_350_000, price_eur: 2058, datasheet_url: '', certifications: ['CE', 'ONVIF', 'IP66'], compatible_with: ['Axis Camera Station'], installation_notes: 'Fisheye outdoor. Zones de passage.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SecuriTech CI' },

  // ═══ NVR (ENREGISTREURS) ═══
  { id: 'eq-033', brand: 'Wisenet', model: 'XRN-3210', category: 'nvr', subcategory: 'NVR 32 canaux', specs: { channels: 32, storage_tb: 0, throughput_mbps: 400, power_watts: 150, h265: true }, price_fcfa: 4_500_000, price_eur: 6860, datasheet_url: '', certifications: ['CE', 'EN 62676'], compatible_with: ['Wisenet WAVE', 'Wisenet cameras'], installation_notes: 'Rack 19". RAID 5 recommandé. 8 baies HDD.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-034', brand: 'Wisenet', model: 'XRN-1610', category: 'nvr', subcategory: 'NVR 16 canaux', specs: { channels: 16, storage_tb: 0, throughput_mbps: 200, power_watts: 100, h265: true }, price_fcfa: 2_800_000, price_eur: 4268, datasheet_url: '', certifications: ['CE'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Rack 19". 4 baies HDD.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-035', brand: 'Axis', model: 'S3008', category: 'nvr', subcategory: 'NVR compact 8 canaux', specs: { channels: 8, storage_tb: 4, throughput_mbps: 100, power_watts: 50, h265: true }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE', 'ONVIF'], compatible_with: ['Axis cameras', 'ONVIF'], installation_notes: 'Compact bureau. Stockage intégré 4TB.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-036', brand: 'Hikvision', model: 'DS-9632NI-M8', category: 'nvr', subcategory: 'NVR 32 canaux 4K', specs: { channels: 32, storage_tb: 0, throughput_mbps: 320, power_watts: 120, h265: true }, price_fcfa: 2_200_000, price_eur: 3354, datasheet_url: '', certifications: ['CE'], compatible_with: ['Hikvision cameras'], installation_notes: 'Rack. 8 baies SATA. Budget.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-037', brand: 'Milestone', model: 'Husky M50', category: 'nvr', subcategory: 'Serveur VMS 64 canaux', specs: { channels: 64, storage_tb: 16, throughput_mbps: 600, power_watts: 350 }, price_fcfa: 8_500_000, price_eur: 12957, datasheet_url: '', certifications: ['CE', 'ONVIF'], compatible_with: ['Multi-marques ONVIF'], installation_notes: 'Serveur VMS ouvert. Multi-marques.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ DISQUES DURS SURVEILLANCE ═══
  { id: 'eq-038', brand: 'Seagate', model: 'SkyHawk 8TB', category: 'nvr', subcategory: 'HDD surveillance 8TB', specs: { storage_tb: 8, power_watts: 7 }, price_fcfa: 320_000, price_eur: 488, datasheet_url: '', certifications: ['CE'], compatible_with: ['Tout NVR SATA'], installation_notes: 'Optimisé surveillance 24/7. 3 ans garantie.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-039', brand: 'WD', model: 'Purple Pro 10TB', category: 'nvr', subcategory: 'HDD surveillance 10TB', specs: { storage_tb: 10, power_watts: 8 }, price_fcfa: 420_000, price_eur: 640, datasheet_url: '', certifications: ['CE'], compatible_with: ['Tout NVR SATA'], installation_notes: 'AI/analytique optimisé. RAID ready.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'Electroplanet CI' },

  // ═══ CONTRÔLE D'ACCÈS — LECTEURS ═══
  { id: 'eq-040', brand: 'HID', model: 'iCLASS SE R40', category: 'badge_reader', subcategory: 'Lecteur multi-techno', specs: { reader_type: 'multi', credential_types: ['iCLASS', 'SEOS', 'Prox', 'Mifare'], weatherproof: true, power_watts: 5 }, price_fcfa: 380_000, price_eur: 579, datasheet_url: '', certifications: ['CE', 'FCC', 'IP55'], compatible_with: ['HID EDGE EVO', 'Lenel', 'C-CURE'], installation_notes: 'Multi-format. Standard mondial.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-041', brand: 'HID', model: 'Signo 40K', category: 'badge_reader', subcategory: 'Lecteur intelligent', specs: { reader_type: 'smart', credential_types: ['SEOS', 'iCLASS', 'Mifare', 'BLE', 'NFC'], weatherproof: true, power_watts: 5 }, price_fcfa: 450_000, price_eur: 686, datasheet_url: '', certifications: ['CE', 'FCC', 'IP55'], compatible_with: ['HID EDGE EVO', 'tout contrôleur OSDP'], installation_notes: 'OSDP v2. Mobile access ready.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-042', brand: 'HID', model: 'pivCLASS R400', category: 'badge_reader', subcategory: 'Lecteur haute sécurité', specs: { reader_type: 'PKI', credential_types: ['PIV', 'SEOS', 'iCLASS'], weatherproof: true, power_watts: 6 }, price_fcfa: 680_000, price_eur: 1036, datasheet_url: '', certifications: ['CE', 'FIPS 201', 'IP55'], compatible_with: ['HID EDGE EVO'], installation_notes: 'Haute sécurité. Zones financières.', maintenance_interval_months: 24, available_abidjan: false, supplier_ci: 'SecuriTech CI' },

  // ═══ BIOMÉTRIE ═══
  { id: 'eq-043', brand: 'Suprema', model: 'BioEntry W2', category: 'biometric_reader', subcategory: 'Lecteur empreinte IP67', specs: { reader_type: 'fingerprint', max_users: 100000, weatherproof: true, power_watts: 8, credential_types: ['empreinte', 'badge', 'PIN'] }, price_fcfa: 720_000, price_eur: 1098, datasheet_url: '', certifications: ['CE', 'IP67', 'IK08'], compatible_with: ['Suprema BioStar 2', 'OSDP'], installation_notes: 'Extérieur. Locaux techniques et serveurs.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-044', brand: 'Suprema', model: 'FaceStation F2', category: 'biometric_reader', subcategory: 'Reconnaissance faciale', specs: { reader_type: 'face', max_users: 50000, weatherproof: false, power_watts: 15, credential_types: ['visage', 'badge', 'PIN'] }, price_fcfa: 1_500_000, price_eur: 2286, datasheet_url: '', certifications: ['CE', 'FCC'], compatible_with: ['Suprema BioStar 2'], installation_notes: 'Intérieur. Accueil VIP et direction.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-045', brand: 'Suprema', model: 'BioLite N2', category: 'biometric_reader', subcategory: 'Multi-biométrique', specs: { reader_type: 'multi', max_users: 20000, weatherproof: true, power_watts: 10, credential_types: ['empreinte', 'visage', 'badge'] }, price_fcfa: 950_000, price_eur: 1448, datasheet_url: '', certifications: ['CE', 'IP65'], compatible_with: ['Suprema BioStar 2'], installation_notes: 'Multi-modal. Back-office sécurité.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },

  // ═══ SERRURES ET CONTRÔLEURS ═══
  { id: 'eq-046', brand: 'Assa Abloy', model: 'Aperio H100', category: 'electric_lock', subcategory: 'Serrure sans fil', specs: { power_watts: 1, credential_types: ['badge'], weatherproof: false, battery_hours: 17520 }, price_fcfa: 420_000, price_eur: 640, datasheet_url: '', certifications: ['CE', 'EN 14846'], compatible_with: ['HID', 'Nedap', 'Lenel'], installation_notes: 'Sans câblage. Portes intérieures.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-047', brand: 'Assa Abloy', model: 'Hi-O Lock', category: 'electric_lock', subcategory: 'Serrure motorisée', specs: { power_watts: 4, weatherproof: false }, price_fcfa: 380_000, price_eur: 579, datasheet_url: '', certifications: ['CE', 'EN 14846'], compatible_with: ['Hi-O Hub'], installation_notes: 'Motorisée. Portes coupe-feu.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-048', brand: 'Dormakaba', model: 'XS4 GxM', category: 'electric_lock', subcategory: 'Béquille électronique', specs: { power_watts: 1, credential_types: ['badge', 'code'], battery_hours: 26000 }, price_fcfa: 350_000, price_eur: 534, datasheet_url: '', certifications: ['CE'], compatible_with: ['Dormakaba Exos'], installation_notes: 'Béquille sur batterie. Bureaux.', maintenance_interval_months: 24, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-049', brand: 'Suprema', model: 'CoreStation', category: 'door_controller', subcategory: 'Contrôleur 4 portes', specs: { power_watts: 20, credential_types: ['badge', 'bio'] }, price_fcfa: 1_200_000, price_eur: 1829, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: ['Suprema BioStar 2'], installation_notes: 'Contrôleur intelligent. 4 portes max.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-050', brand: 'HID', model: 'EDGE EVO Solo', category: 'door_controller', subcategory: 'Contrôleur IP 1 porte', specs: { power_watts: 8, credential_types: ['badge'] }, price_fcfa: 550_000, price_eur: 838, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: ['HID readers'], installation_notes: 'IP natif. 1 porte. PoE possible.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },

  // ═══ TOURNIQUETS ET BARRIÈRES ═══
  { id: 'eq-051', brand: 'CAME', model: 'GT4 Tourniquet', category: 'turnstile', subcategory: 'Tourniquet tripode', specs: { power_watts: 35, weatherproof: false }, price_fcfa: 2_800_000, price_eur: 4268, datasheet_url: '', certifications: ['CE'], compatible_with: ['Tout contrôleur'], installation_notes: 'Entrée employés et fournisseurs.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-052', brand: 'Dormakaba', model: 'Argus HSB-M03', category: 'turnstile', subcategory: 'Portillon vitré', specs: { power_watts: 50, weatherproof: false }, price_fcfa: 4_500_000, price_eur: 6860, datasheet_url: '', certifications: ['CE', 'EN 14351'], compatible_with: ['Dormakaba Exos'], installation_notes: 'Portillon premium. Hall VIP.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-053', brand: 'CAME', model: 'GARD GT8', category: 'barrier', subcategory: 'Barrière parking', specs: { power_watts: 200, weatherproof: true }, price_fcfa: 1_500_000, price_eur: 2286, datasheet_url: '', certifications: ['CE', 'IP54'], compatible_with: ['CAME Connect'], installation_notes: 'Barrière 8m. Parking B1.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-054', brand: 'CAME', model: 'BPT Interphone', category: 'interphone', subcategory: 'Interphone IP vidéo', specs: { power_watts: 10, screen_size_inch: 7, weatherproof: true }, price_fcfa: 450_000, price_eur: 686, datasheet_url: '', certifications: ['CE', 'IP54'], compatible_with: ['CAME BPT'], installation_notes: 'Vidéo IP. Entrées livraison.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ INCENDIE — DÉTECTION ═══
  { id: 'eq-055', brand: 'Siemens', model: 'FDI241', category: 'smoke_detector', subcategory: 'Détecteur optique fumée', specs: { detection_type: 'optical', coverage_m2: 60, power_watts: 0.5 }, price_fcfa: 85_000, price_eur: 130, datasheet_url: '', certifications: ['CE', 'EN 54-7', 'NF'], compatible_with: ['Siemens Cerberus'], installation_notes: 'Plafond. 1 par 60m². NF obligatoire CI.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-056', brand: 'Siemens', model: 'FDO241', category: 'smoke_detector', subcategory: 'Détecteur optique adressable', specs: { detection_type: 'optical_addressable', coverage_m2: 60, power_watts: 0.5 }, price_fcfa: 120_000, price_eur: 183, datasheet_url: '', certifications: ['CE', 'EN 54-7', 'NF'], compatible_with: ['Siemens Cerberus'], installation_notes: 'Adressable. Identification précise.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-057', brand: 'Honeywell', model: 'HFS-P Smoke', category: 'smoke_detector', subcategory: 'Détecteur photoélectrique', specs: { detection_type: 'photoelectric', coverage_m2: 60, power_watts: 0.4 }, price_fcfa: 75_000, price_eur: 114, datasheet_url: '', certifications: ['CE', 'EN 54-7', 'UL'], compatible_with: ['Honeywell Morley'], installation_notes: 'Budget. Compatible Honeywell.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-058', brand: 'Honeywell', model: 'FSP-851', category: 'smoke_detector', subcategory: 'Détecteur intelligent', specs: { detection_type: 'intelligent', coverage_m2: 80, power_watts: 0.5 }, price_fcfa: 150_000, price_eur: 229, datasheet_url: '', certifications: ['CE', 'EN 54-7', 'UL'], compatible_with: ['Honeywell Notifier'], installation_notes: 'Intelligent. Auto-diagnostic.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-059', brand: 'Siemens', model: 'FDCAI241', category: 'heat_detector', subcategory: 'Détecteur thermique', specs: { detection_type: 'heat_ROR', coverage_m2: 20, power_watts: 0.4, response_time_sec: 30 }, price_fcfa: 95_000, price_eur: 145, datasheet_url: '', certifications: ['CE', 'EN 54-5', 'NF'], compatible_with: ['Siemens Cerberus'], installation_notes: 'Cuisines. Zones humides ou poussiéreuses.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-060', brand: 'Honeywell', model: 'TC808B1', category: 'heat_detector', subcategory: 'Détecteur thermostatique', specs: { detection_type: 'heat_fixed', coverage_m2: 20, power_watts: 0.3 }, price_fcfa: 65_000, price_eur: 99, datasheet_url: '', certifications: ['CE', 'EN 54-5'], compatible_with: ['Honeywell Morley'], installation_notes: 'Seuil fixe 58°C. Parkings.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },

  // ═══ INCENDIE — DÉCLENCHEURS ET ALARMES ═══
  { id: 'eq-061', brand: 'Tyco', model: 'CP820M', category: 'manual_call_point', subcategory: 'Déclencheur manuel', specs: { power_watts: 0, weatherproof: false }, price_fcfa: 45_000, price_eur: 69, datasheet_url: '', certifications: ['CE', 'EN 54-11', 'NF'], compatible_with: ['Tout SSI'], installation_notes: '1.30m du sol. Près sorties. Rouge.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-062', brand: 'Tyco', model: 'MR601TEX', category: 'manual_call_point', subcategory: 'Déclencheur extérieur', specs: { power_watts: 0, weatherproof: true }, price_fcfa: 65_000, price_eur: 99, datasheet_url: '', certifications: ['CE', 'EN 54-11', 'IP67'], compatible_with: ['Tout SSI'], installation_notes: 'Extérieur IP67. Sorties secours.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-063', brand: 'Tyco', model: 'SpectrAlert Advance', category: 'fire_alarm_panel', subcategory: 'Sirène flash', specs: { db_level: 90, power_watts: 2, weatherproof: false }, price_fcfa: 120_000, price_eur: 183, datasheet_url: '', certifications: ['CE', 'EN 54-3', 'UL'], compatible_with: ['Tout SSI'], installation_notes: 'Sirène + flash. Zones bruyantes.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-064', brand: 'Siemens', model: 'FC726 Cerberus', category: 'fire_alarm_panel', subcategory: 'Centrale incendie 2 boucles', specs: { power_watts: 200, channels: 2 }, price_fcfa: 3_500_000, price_eur: 5335, datasheet_url: '', certifications: ['CE', 'EN 54-2', 'NF', 'APSAD'], compatible_with: ['Siemens détecteurs'], installation_notes: 'Centrale 2 boucles. PC sécurité.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-065', brand: 'Honeywell', model: 'Notifier NFS2-3030', category: 'fire_alarm_panel', subcategory: 'Centrale incendie 10 boucles', specs: { power_watts: 250, channels: 10 }, price_fcfa: 6_800_000, price_eur: 10366, datasheet_url: '', certifications: ['CE', 'EN 54-2', 'UL', 'APSAD'], compatible_with: ['Honeywell détecteurs'], installation_notes: 'Grande capacité. Centres commerciaux.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },

  // ═══ INCENDIE — SPRINKLERS ═══
  { id: 'eq-066', brand: 'Tyco', model: 'TY-B K5.6', category: 'sprinkler_head', subcategory: 'Sprinkler pendant K5.6', specs: { coverage_m2: 12, response_time_sec: 5 }, price_fcfa: 25_000, price_eur: 38, datasheet_url: '', certifications: ['CE', 'EN 12259', 'APSAD'], compatible_with: [], installation_notes: '1 par 12m². Pendant. T68°C.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-067', brand: 'Viking', model: 'VK302 ESFR', category: 'sprinkler_head', subcategory: 'Sprinkler ESFR K14', specs: { coverage_m2: 9, response_time_sec: 3 }, price_fcfa: 45_000, price_eur: 69, datasheet_url: '', certifications: ['CE', 'EN 12259', 'FM'], compatible_with: [], installation_notes: 'Réponse rapide. Stockage haute.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },

  // ═══ ÉCLAIRAGE SECOURS ═══
  { id: 'eq-068', brand: 'Legrand', model: 'BAES SATI', category: 'emergency_light', subcategory: 'Bloc autonome SATI', specs: { battery_hours: 1, power_watts: 8, brightness_nits: 45 }, price_fcfa: 65_000, price_eur: 99, datasheet_url: '', certifications: ['CE', 'NF AEAS', 'EN 60598'], compatible_with: [], installation_notes: 'Au-dessus sorties. 1h autonomie.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-069', brand: 'Legrand', model: 'BAES SATI Adressable', category: 'emergency_light', subcategory: 'BAES adressable', specs: { battery_hours: 1, power_watts: 8 }, price_fcfa: 120_000, price_eur: 183, datasheet_url: '', certifications: ['CE', 'NF AEAS'], compatible_with: ['Legrand Mosaic'], installation_notes: 'Adressable. Télé-commande centralisée.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-070', brand: 'Cooper', model: 'Illumina LED', category: 'emergency_light', subcategory: 'Éclairage secours LED', specs: { battery_hours: 3, power_watts: 5 }, price_fcfa: 85_000, price_eur: 130, datasheet_url: '', certifications: ['CE', 'EN 60598'], compatible_with: [], installation_notes: 'LED 3h autonomie. Escaliers.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },

  // ═══ BARRE ANTI-PANIQUE ═══
  { id: 'eq-071', brand: 'Geze', model: 'E212N', category: 'panic_bar', subcategory: 'Barre anti-panique 1 point', specs: { power_watts: 0, weatherproof: false }, price_fcfa: 180_000, price_eur: 274, datasheet_url: '', certifications: ['CE', 'EN 1125'], compatible_with: [], installation_notes: 'Sorties secours. 1 point de fermeture.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-072', brand: 'Geze', model: 'TS 5000', category: 'panic_bar', subcategory: 'Ferme-porte', specs: { power_watts: 0 }, price_fcfa: 120_000, price_eur: 183, datasheet_url: '', certifications: ['CE', 'EN 1154'], compatible_with: [], installation_notes: 'Ferme-porte toutes portes coupe-feu.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-073', brand: 'Dormakaba', model: 'PHB 3000', category: 'panic_bar', subcategory: 'Barre anti-panique 3 points', specs: { power_watts: 0 }, price_fcfa: 280_000, price_eur: 427, datasheet_url: '', certifications: ['CE', 'EN 1125', 'EN 179'], compatible_with: [], installation_notes: '3 points fermeture. Haute sécurité.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ SIGNALÉTIQUE — TOTEMS ═══
  { id: 'eq-074', brand: 'Custom', model: 'Totem Wayfinding 3m', category: 'wayfinding_totem', subcategory: 'Totem directionnel 3m', specs: { dimensions_mm: '400x400x3000', weight_kg: 45 }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Sol béton. Ancrage 4 points. Éclairé LED.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-075', brand: 'Custom', model: 'Totem Wayfinding 5m', category: 'wayfinding_totem', subcategory: 'Totem directionnel 5m', specs: { dimensions_mm: '600x600x5000', weight_kg: 85 }, price_fcfa: 3_200_000, price_eur: 4878, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Ancrage béton renforcé. Hall principal.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-076', brand: 'Custom', model: 'Totem Directory', category: 'directory_board', subcategory: 'Répertoire enseignes', specs: { dimensions_mm: '800x200x2500', weight_kg: 35 }, price_fcfa: 1_200_000, price_eur: 1829, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Entrées principales. Liste enseignes.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },

  // ═══ SIGNALÉTIQUE — ÉCRANS DIGITAUX ═══
  { id: 'eq-077', brand: 'Samsung', model: 'OH46B', category: 'digital_signage', subcategory: 'Écran outdoor 46"', specs: { screen_size_inch: 46, brightness_nits: 3500, power_watts: 150, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 3_500_000, price_eur: 5335, datasheet_url: '', certifications: ['CE', 'IP56'], compatible_with: ['Samsung MagicINFO'], installation_notes: 'Extérieur. 3500 nits lisible soleil.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-078', brand: 'Samsung', model: 'OM55B', category: 'digital_signage', subcategory: 'Écran indoor 55"', specs: { screen_size_inch: 55, brightness_nits: 4000, power_watts: 120, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 2_800_000, price_eur: 4268, datasheet_url: '', certifications: ['CE'], compatible_with: ['Samsung MagicINFO'], installation_notes: 'Intérieur haute luminosité. Vitrines.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-079', brand: 'LG', model: '49XS4J', category: 'digital_signage', subcategory: 'Écran vitrine 49"', specs: { screen_size_inch: 49, brightness_nits: 4000, power_watts: 110, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 2_200_000, price_eur: 3354, datasheet_url: '', certifications: ['CE'], compatible_with: ['LG SuperSign'], installation_notes: 'Vitrine. Anti-reflet.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-080', brand: 'LG', model: '55XS4J', category: 'digital_signage', subcategory: 'Écran vitrine 55"', specs: { screen_size_inch: 55, brightness_nits: 4000, power_watts: 130, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 2_600_000, price_eur: 3963, datasheet_url: '', certifications: ['CE'], compatible_with: ['LG SuperSign'], installation_notes: 'Grand format vitrine.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },

  // ═══ BORNES INTERACTIVES ═══
  { id: 'eq-081', brand: 'Elo', model: 'I-Series 22"', category: 'digital_signage', subcategory: 'Borne interactive 22"', specs: { screen_size_inch: 22, brightness_nits: 250, power_watts: 50, connectivity: ['USB', 'WiFi', 'LAN'] }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Tactile. Wayfinding indoor.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-082', brand: 'Custom', model: 'Borne Kiosk 42"', category: 'digital_signage', subcategory: 'Borne kiosk 42"', specs: { screen_size_inch: 42, brightness_nits: 500, power_watts: 100, connectivity: ['WiFi', 'LAN'] }, price_fcfa: 3_200_000, price_eur: 4878, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Kiosk totem tactile. Info visiteurs.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SignaPrint CI' },

  // ═══ PARKING GUIDANCE ═══
  { id: 'eq-083', brand: 'Quercus', model: 'PGS Sensor LED', category: 'parking_guidance', subcategory: 'Capteur place parking', specs: { power_watts: 2, connectivity: ['RS485'] }, price_fcfa: 85_000, price_eur: 130, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Quercus PGS'], installation_notes: 'Au-dessus chaque place. LED vert/rouge.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-084', brand: 'Quercus', model: 'PGS Display', category: 'parking_guidance', subcategory: 'Afficheur places libres', specs: { power_watts: 15, screen_size_inch: 32 }, price_fcfa: 450_000, price_eur: 686, datasheet_url: '', certifications: ['CE'], compatible_with: ['Quercus PGS'], installation_notes: 'Entrées parking. Places disponibles.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },

  // ═══ QR CODE STANDS ═══
  { id: 'eq-085', brand: 'Custom', model: 'QR Stand A4', category: 'qr_code_stand', subcategory: 'Support QR code A4', specs: { dimensions_mm: '210x297x1200', weight_kg: 3 }, price_fcfa: 35_000, price_eur: 53, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Devant enseignes. QR Cosmos Club.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-086', brand: 'Custom', model: 'QR Table Stand', category: 'qr_code_stand', subcategory: 'Chevalet QR table', specs: { dimensions_mm: '150x200x5', weight_kg: 0.3 }, price_fcfa: 8_000, price_eur: 12, datasheet_url: '', certifications: [], compatible_with: [], installation_notes: 'Tables food court. QR menu.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },

  // ═══ SWITCHES RÉSEAU ═══
  { id: 'eq-087', brand: 'Cisco', model: 'CBS350-24FP-4G', category: 'nvr', subcategory: 'Switch PoE+ 24 ports', specs: { channels: 24, power_watts: 400, throughput_mbps: 1000 }, price_fcfa: 1_200_000, price_eur: 1829, datasheet_url: '', certifications: ['CE'], compatible_with: ['Toutes caméras PoE'], installation_notes: 'Switch PoE+ 370W. Rack 19".', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-088', brand: 'Cisco', model: 'CBS350-48FP-4G', category: 'nvr', subcategory: 'Switch PoE+ 48 ports', specs: { channels: 48, power_watts: 740, throughput_mbps: 1000 }, price_fcfa: 2_400_000, price_eur: 3659, datasheet_url: '', certifications: ['CE'], compatible_with: ['Toutes caméras PoE'], installation_notes: 'Switch PoE+ 740W. Rack 19".', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },

  // ═══ PANNEAU SIGNALÉTIQUE CLASSIQUE ═══
  { id: 'eq-089', brand: 'Custom', model: 'Panneau Dir. Suspendu', category: 'wayfinding_totem', subcategory: 'Panneau suspendu', specs: { dimensions_mm: '1200x400x30', weight_kg: 8 }, price_fcfa: 180_000, price_eur: 274, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Suspension plafond. Câbles inox.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-090', brand: 'Custom', model: 'Panneau Dir. Mural', category: 'wayfinding_totem', subcategory: 'Panneau mural', specs: { dimensions_mm: '800x300x20', weight_kg: 4 }, price_fcfa: 120_000, price_eur: 183, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Fixation murale. Vis inox.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-091', brand: 'Custom', model: 'Bannière Suspendue', category: 'wayfinding_totem', subcategory: 'Bannière tissu', specs: { dimensions_mm: '600x2000', weight_kg: 2 }, price_fcfa: 85_000, price_eur: 130, datasheet_url: '', certifications: [], compatible_with: [], installation_notes: 'Tissu M1. Suspension galerie.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-092', brand: 'Custom', model: 'Marquage Sol', category: 'wayfinding_totem', subcategory: 'Adhésif sol directionnel', specs: { dimensions_mm: '300x1000', weight_kg: 0.5 }, price_fcfa: 25_000, price_eur: 38, datasheet_url: '', certifications: ['CE', 'R10 antidérapant'], compatible_with: [], installation_notes: 'Adhésif antidérapant R10. Sol propre.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-093', brand: 'Custom', model: 'Plaque Porte Alu', category: 'wayfinding_totem', subcategory: 'Plaque signalétique porte', specs: { dimensions_mm: '200x150x3', weight_kg: 0.3 }, price_fcfa: 15_000, price_eur: 23, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Aluminium brossé. Vissée ou collée.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-094', brand: 'Custom', model: 'Pictogramme PMR', category: 'wayfinding_totem', subcategory: 'Picto accessibilité ISO', specs: { dimensions_mm: '200x200x3', weight_kg: 0.2 }, price_fcfa: 12_000, price_eur: 18, datasheet_url: '', certifications: ['CE', 'ISO 7010'], compatible_with: [], installation_notes: 'ISO 7010. Ascenseurs et rampes.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-095', brand: 'Custom', model: 'Panneau Toilettes', category: 'wayfinding_totem', subcategory: 'Panneau sanitaires', specs: { dimensions_mm: '250x250x3', weight_kg: 0.4 }, price_fcfa: 18_000, price_eur: 27, datasheet_url: '', certifications: ['CE', 'ISO 7010'], compatible_with: [], installation_notes: 'Picto ISO. Éclairé si possible.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-096', brand: 'Legrand', model: 'Sortie Secours LED', category: 'wayfinding_totem', subcategory: 'Bloc sortie de secours', specs: { power_watts: 4, battery_hours: 1, brightness_nits: 500 }, price_fcfa: 55_000, price_eur: 84, datasheet_url: '', certifications: ['CE', 'NF AEAS', 'EN 60598'], compatible_with: [], installation_notes: 'Au-dessus sorties secours. LED vert.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-097', brand: 'Custom', model: 'Plan Évacuation A3', category: 'wayfinding_totem', subcategory: 'Plan évacuation', specs: { dimensions_mm: '420x297x5', weight_kg: 0.5 }, price_fcfa: 35_000, price_eur: 53, datasheet_url: '', certifications: ['CE', 'NF ISO 23601'], compatible_with: [], installation_notes: 'NF ISO 23601. Chaque étage.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-098', brand: 'Custom', model: 'Interdiction Fumée', category: 'wayfinding_totem', subcategory: 'Panneau interdiction', specs: { dimensions_mm: '200x200x3', weight_kg: 0.2 }, price_fcfa: 10_000, price_eur: 15, datasheet_url: '', certifications: ['ISO 7010'], compatible_with: [], installation_notes: 'ISO 7010 P002. Toutes zones.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },

  // ═══ CÂBLAGE ET ACCESSOIRES ═══
  { id: 'eq-099', brand: 'Nexans', model: 'Cat6 U/FTP 305m', category: 'nvr', subcategory: 'Câble réseau Cat6', specs: { dimensions_mm: '305000' }, price_fcfa: 280_000, price_eur: 427, datasheet_url: '', certifications: ['CE', 'Cat6'], compatible_with: ['Tout PoE'], installation_notes: 'Bobine 305m. U/FTP blindé.', maintenance_interval_months: 120, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-100', brand: 'Nexans', model: 'Cat6A S/FTP 305m', category: 'nvr', subcategory: 'Câble réseau Cat6A', specs: { dimensions_mm: '305000' }, price_fcfa: 420_000, price_eur: 640, datasheet_url: '', certifications: ['CE', 'Cat6A'], compatible_with: ['Tout PoE+'], installation_notes: 'Bobine 305m. 10Gbps. PoE++.', maintenance_interval_months: 120, available_abidjan: true, supplier_ci: 'Electroplanet CI' },

  // ═══ ÉQUIPEMENTS COMPLÉMENTAIRES (101-155) ═══
  { id: 'eq-101', brand: 'APC', model: 'Smart-UPS 1500VA', category: 'nvr', subcategory: 'Onduleur 1500VA', specs: { power_watts: 980, battery_hours: 0.5 }, price_fcfa: 850_000, price_eur: 1295, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: [], installation_notes: 'Rack 19". NVR et switches.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-102', brand: 'APC', model: 'Smart-UPS 3000VA', category: 'nvr', subcategory: 'Onduleur 3000VA', specs: { power_watts: 2100, battery_hours: 0.5 }, price_fcfa: 1_600_000, price_eur: 2439, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: [], installation_notes: 'Rack 19". Salle serveur.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-103', brand: 'APC', model: 'Smart-UPS 5000VA', category: 'nvr', subcategory: 'Onduleur 5000VA', specs: { power_watts: 4000, battery_hours: 0.3 }, price_fcfa: 3_200_000, price_eur: 4878, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: [], installation_notes: 'Infrastructure critique.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-104', brand: 'Bosch', model: 'MIC IP 7100i', category: 'camera_ptz', subcategory: 'PTZ robuste 2MP', specs: { resolution: '2MP', fov: 120, rangeM: 30, ip_rating: 'IP68', ik_rating: 'IK10', power_watts: 60, h265: true, wdr: true, ir_range_m: 120 }, price_fcfa: 5_200_000, price_eur: 7927, datasheet_url: '', certifications: ['CE', 'IP68', 'IK10'], compatible_with: ['Bosch VMS'], installation_notes: 'Conditions extrêmes. Périmètre.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-105', brand: 'JVC', model: 'VN-H157WPU', category: 'camera_dome', subcategory: 'Dôme compact 2MP', specs: { resolution: '2MP', fov: 95, rangeM: 8, ip_rating: 'IP66', power_watts: 8, poe: true, h265: false, wdr: true }, price_fcfa: 380_000, price_eur: 579, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['ONVIF'], installation_notes: 'Budget compact. Zones secondaires.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-106', brand: 'Dahua', model: 'SD6AL245XA', category: 'camera_ptz', subcategory: 'PTZ AI 2MP', specs: { resolution: '2MP', fov: 120, rangeM: 40, ip_rating: 'IP67', power_watts: 55, h265: true, wdr: true, ir_range_m: 250 }, price_fcfa: 2_100_000, price_eur: 3201, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Dahua DSS'], installation_notes: 'PTZ AI. Tracking auto.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  // Additional items to reach 150+
  { id: 'eq-107', brand: 'Honeywell', model: 'MAXPRO NVR SE', category: 'nvr', subcategory: 'NVR 64ch enterprise', specs: { channels: 64, storage_tb: 24, throughput_mbps: 512, power_watts: 300 }, price_fcfa: 7_500_000, price_eur: 11433, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: ['ONVIF'], installation_notes: 'Enterprise. Multi-site.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-108', brand: 'Wisenet', model: 'XRN-6410B2', category: 'nvr', subcategory: 'NVR 64 canaux RAID', specs: { channels: 64, storage_tb: 0, throughput_mbps: 512, power_watts: 200, h265: true }, price_fcfa: 6_200_000, price_eur: 9451, datasheet_url: '', certifications: ['CE'], compatible_with: ['Wisenet WAVE'], installation_notes: 'RAID intégré. 8 baies.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-109', brand: 'Hikvision', model: 'DS-K1T342MX', category: 'biometric_reader', subcategory: 'Terminal facial MinMoe', specs: { reader_type: 'face', max_users: 10000, power_watts: 12, credential_types: ['visage', 'badge'] }, price_fcfa: 680_000, price_eur: 1036, datasheet_url: '', certifications: ['CE'], compatible_with: ['Hikvision ACS'], installation_notes: 'Reconnaissance faciale budget.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-110', brand: 'ZKTeco', model: 'SpeedFace V5L', category: 'biometric_reader', subcategory: 'Terminal multi-biométrique', specs: { reader_type: 'multi', max_users: 10000, power_watts: 12, credential_types: ['visage', 'paume', 'badge'] }, price_fcfa: 520_000, price_eur: 793, datasheet_url: '', certifications: ['CE'], compatible_with: ['ZKTeco ZKBioSecurity'], installation_notes: 'Visage + paume. Budget.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-111', brand: 'Salto', model: 'XS4 Mini', category: 'electric_lock', subcategory: 'Serrure électronique mini', specs: { power_watts: 1, battery_hours: 20000, credential_types: ['badge', 'mobile'] }, price_fcfa: 320_000, price_eur: 488, datasheet_url: '', certifications: ['CE'], compatible_with: ['Salto Space'], installation_notes: 'Sans câblage. Portes bureaux.', maintenance_interval_months: 24, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-112', brand: 'CAME', model: 'GARD PX', category: 'barrier', subcategory: 'Barrière rapide parking', specs: { power_watts: 250, weatherproof: true }, price_fcfa: 2_200_000, price_eur: 3354, datasheet_url: '', certifications: ['CE', 'IP54'], compatible_with: ['CAME Connect'], installation_notes: 'Ouverture 1.5s. Parking haute rotation.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-113', brand: 'Custom', model: 'Numéro Cellule LED', category: 'wayfinding_totem', subcategory: 'Numéro cellule rétro-éclairé', specs: { power_watts: 3, dimensions_mm: '300x200x30' }, price_fcfa: 45_000, price_eur: 69, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'LED intégré. Au-dessus cellules.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-114', brand: 'Custom', model: 'Enseigne Façade LED', category: 'digital_signage', subcategory: 'Enseigne lumineuse façade', specs: { power_watts: 50, dimensions_mm: '2000x500x100' }, price_fcfa: 650_000, price_eur: 991, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Façade centre commercial. Aluminium.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-115', brand: 'Vivotek', model: 'FD9389-EHTV', category: 'camera_dome', subcategory: 'Dôme outdoor 5MP', specs: { resolution: '5MP', fov: 105, rangeM: 12, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 15, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 620_000, price_eur: 945, datasheet_url: '', certifications: ['CE', 'IP66', 'IK10'], compatible_with: ['ONVIF'], installation_notes: 'Alternative budget. Extérieur.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-116', brand: 'Hanwha', model: 'ANE-L7012R', category: 'camera_bullet', subcategory: 'Bullet AI 4MP', specs: { resolution: '4MP', fov: 100, rangeM: 14, ip_rating: 'IP66', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 25 }, price_fcfa: 720_000, price_eur: 1098, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'AI edge. Détection véhicule/personne.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-117', brand: 'Wisenet', model: 'WAVE Server', category: 'video_analytics_server', subcategory: 'Serveur VMS WAVE', specs: { channels: 128, power_watts: 500, throughput_mbps: 1000 }, price_fcfa: 12_000_000, price_eur: 18294, datasheet_url: '', certifications: ['CE'], compatible_with: ['Wisenet cameras', 'ONVIF'], installation_notes: 'Serveur VMS central. 128 canaux.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-118', brand: 'Agent Vi', model: 'innoVi', category: 'video_analytics_server', subcategory: 'Analytique vidéo cloud', specs: { channels: 64, power_watts: 300 }, price_fcfa: 8_500_000, price_eur: 12957, datasheet_url: '', certifications: ['CE'], compatible_with: ['Multi-marques'], installation_notes: 'Analytique cloud. Comptage, détection.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-119', brand: 'Axis', model: 'A1601', category: 'door_controller', subcategory: 'Contrôleur porte réseau', specs: { power_watts: 12, credential_types: ['badge', 'bio'] }, price_fcfa: 650_000, price_eur: 991, datasheet_url: '', certifications: ['CE', 'ONVIF'], compatible_with: ['Axis readers', 'OSDP'], installation_notes: 'Contrôleur IP 2 portes. PoE.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-120', brand: 'Notifier', model: 'FSP-951R', category: 'smoke_detector', subcategory: 'Détecteur laser premium', specs: { detection_type: 'laser', coverage_m2: 80, power_watts: 0.5 }, price_fcfa: 220_000, price_eur: 335, datasheet_url: '', certifications: ['CE', 'EN 54-7', 'UL'], compatible_with: ['Notifier NFS2'], installation_notes: 'Laser haute sensibilité. Data centers.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-121', brand: 'Esser', model: 'IQ8Quad', category: 'smoke_detector', subcategory: 'Multi-capteur 4 en 1', specs: { detection_type: 'multi', coverage_m2: 60, power_watts: 0.5 }, price_fcfa: 180_000, price_eur: 274, datasheet_url: '', certifications: ['CE', 'EN 54-5/7', 'NF'], compatible_with: ['Esser FlexES'], installation_notes: 'Fumée + chaleur + CO + flamme.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-122', brand: 'Custom', model: 'Rack 19" 42U', category: 'nvr', subcategory: 'Baie serveur 42U', specs: { dimensions_mm: '600x800x2000', weight_kg: 85 }, price_fcfa: 650_000, price_eur: 991, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Baie 42U. Salle serveur.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-123', brand: 'Custom', model: 'Rack 19" 12U', category: 'nvr', subcategory: 'Baie murale 12U', specs: { dimensions_mm: '600x450x600', weight_kg: 25 }, price_fcfa: 180_000, price_eur: 274, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Murale. Locaux techniques.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-124', brand: 'Mobotix', model: 'M73', category: 'camera_dome', subcategory: 'Dôme modulaire 4K', specs: { resolution: '8MP', fov: 95, rangeM: 10, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 12, poe: true }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE', 'IP66', 'IK10'], compatible_with: ['Mobotix Hub'], installation_notes: 'Modulaire. Capteur interchangeable.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-125', brand: 'Pelco', model: 'Spectra Pro 2', category: 'camera_ptz', subcategory: 'PTZ haute performance', specs: { resolution: '2MP', fov: 120, rangeM: 40, ip_rating: 'IP66', power_watts: 55, h265: true, wdr: true, ir_range_m: 100 }, price_fcfa: 3_800_000, price_eur: 5793, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Pelco VX Pro'], installation_notes: 'Haute performance. Sites critiques.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-126', brand: 'LG', model: '86UH5J', category: 'digital_signage', subcategory: 'Écran UHD 86"', specs: { screen_size_inch: 86, brightness_nits: 500, power_watts: 280, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 4_500_000, price_eur: 6860, datasheet_url: '', certifications: ['CE'], compatible_with: ['LG SuperSign'], installation_notes: 'Grand format. Atrium.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-127', brand: 'Schneider', model: 'Harmony STB', category: 'fire_alarm_panel', subcategory: 'Système de sécurité incendie intégré', specs: { power_watts: 300, channels: 8 }, price_fcfa: 5_500_000, price_eur: 8384, datasheet_url: '', certifications: ['CE', 'NF', 'APSAD'], compatible_with: ['Schneider detecteurs'], installation_notes: 'SSI intégré. Grands ERP.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-128', brand: 'Hikvision', model: 'DS-2CD2146G2', category: 'camera_dome', subcategory: 'Dôme AcuSense 4MP', specs: { resolution: '4MP', fov: 106, rangeM: 10, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 420_000, price_eur: 640, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Hikvision iVMS'], installation_notes: 'AcuSense budget. Commerces.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-129', brand: 'Dahua', model: 'NVR5232-EI', category: 'nvr', subcategory: 'NVR AI 32ch', specs: { channels: 32, storage_tb: 0, throughput_mbps: 384, power_watts: 120, h265: true }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE'], compatible_with: ['Dahua cameras'], installation_notes: 'NVR AI intégré. Budget.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-130', brand: 'Suprema', model: 'X-Station 2', category: 'biometric_reader', subcategory: 'Terminal multi-biométrique IP', specs: { reader_type: 'multi', max_users: 100000, power_watts: 15, credential_types: ['visage', 'empreinte', 'badge', 'QR', 'mobile'] }, price_fcfa: 1_800_000, price_eur: 2744, datasheet_url: '', certifications: ['CE', 'IP65'], compatible_with: ['Suprema BioStar 2'], installation_notes: 'Premium multi-modal. Direction.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-131', brand: 'FLIR', model: 'FC-324-R', category: 'camera_bullet', subcategory: 'Caméra thermique', specs: { resolution: 'VGA', fov: 24, rangeM: 100, ip_rating: 'IP66', power_watts: 20, poe: true }, price_fcfa: 6_500_000, price_eur: 9909, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['ONVIF'], installation_notes: 'Thermique. Détection périmétrique.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-132', brand: 'Wisenet', model: 'TNM-3620TDY', category: 'camera_multidirectional', subcategory: 'Multi AI + Thermal', specs: { resolution: '2MP+VGA', fov: 180, rangeM: 15, ip_rating: 'IP66', power_watts: 30, poe: true, h265: true }, price_fcfa: 3_800_000, price_eur: 5793, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Visible + thermique. Périmètre.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-133', brand: 'Custom', model: 'Panneau Plan Vous Êtes Ici', category: 'directory_board', subcategory: 'Plan "Vous êtes ici"', specs: { dimensions_mm: '800x600x30', weight_kg: 5 }, price_fcfa: 85_000, price_eur: 130, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Aux intersections. Éclairé.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-134', brand: 'Nedap', model: 'AEOS Blue', category: 'door_controller', subcategory: 'Contrôleur IP intelligent', specs: { power_watts: 15, credential_types: ['badge', 'mobile', 'QR'] }, price_fcfa: 980_000, price_eur: 1494, datasheet_url: '', certifications: ['CE'], compatible_with: ['HID', 'OSDP'], installation_notes: 'Contrôleur cloud-ready. Mobile access.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-135', brand: 'Genetec', model: 'Synergis Cloud Link', category: 'door_controller', subcategory: 'Contrôleur intelligent cloud', specs: { power_watts: 20, credential_types: ['badge', 'mobile'] }, price_fcfa: 1_500_000, price_eur: 2286, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: ['Genetec Security Center'], installation_notes: 'Cloud hybride. Multi-site.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-136', brand: 'Boon Edam', model: 'Speedlane Lifeline', category: 'turnstile', subcategory: 'Couloir rapide sécurisé', specs: { power_watts: 60, weatherproof: false }, price_fcfa: 5_500_000, price_eur: 8384, datasheet_url: '', certifications: ['CE', 'EN 14351'], compatible_with: ['Tout contrôleur'], installation_notes: 'Couloir vitré premium. Hall direction.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-137', brand: 'CAME', model: 'GARD GT4 Auto', category: 'barrier', subcategory: 'Barrière automatique 4m', specs: { power_watts: 150, weatherproof: true }, price_fcfa: 1_100_000, price_eur: 1677, datasheet_url: '', certifications: ['CE', 'IP54'], compatible_with: ['CAME Connect'], installation_notes: 'Barrière 4m. Entrées secondaires.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-138', brand: 'Commend', model: 'OD10e', category: 'interphone', subcategory: 'Interphone SIP outdoor', specs: { power_watts: 8, weatherproof: true }, price_fcfa: 380_000, price_eur: 579, datasheet_url: '', certifications: ['CE', 'IP65'], compatible_with: ['SIP', 'VoIP'], installation_notes: 'SIP/VoIP. Entrées de service.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-139', brand: 'Viking', model: 'Sprinkler Concealed', category: 'sprinkler_head', subcategory: 'Sprinkler encastré', specs: { coverage_m2: 12, response_time_sec: 5 }, price_fcfa: 35_000, price_eur: 53, datasheet_url: '', certifications: ['CE', 'EN 12259'], compatible_with: [], installation_notes: 'Encastré plafond. Esthétique.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-140', brand: 'Custom', model: 'Enseigne Cellule Rétro', category: 'digital_signage', subcategory: 'Enseigne cellule rétro-éclairée', specs: { power_watts: 30, dimensions_mm: '1500x400x80' }, price_fcfa: 350_000, price_eur: 534, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Face cellule. Aluminium + LED.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-141', brand: 'Samsung', model: 'QB75B', category: 'digital_signage', subcategory: 'Écran commercial 75"', specs: { screen_size_inch: 75, brightness_nits: 350, power_watts: 185, connectivity: ['HDMI', 'USB', 'WiFi', 'LAN'] }, price_fcfa: 2_200_000, price_eur: 3354, datasheet_url: '', certifications: ['CE'], compatible_with: ['Samsung MagicINFO'], installation_notes: 'Intérieur. Murs vidéo.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-142', brand: 'Wisenet', model: 'QNE-8011R', category: 'camera_bullet', subcategory: 'Bullet compact 5MP', specs: { resolution: '5MP', fov: 94, rangeM: 12, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 10, poe: true, h265: true, wdr: true, ir_range_m: 20 }, price_fcfa: 650_000, price_eur: 991, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Compact bullet. Allées.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-143', brand: 'Axis', model: 'P3265-LV', category: 'camera_dome', subcategory: 'Dôme DLPU 2MP', specs: { resolution: '2MP', fov: 110, rangeM: 10, ip_rating: 'IP52', ik_rating: 'IK08', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 20 }, price_fcfa: 680_000, price_eur: 1036, datasheet_url: '', certifications: ['CE', 'ONVIF'], compatible_with: ['Axis Camera Station'], installation_notes: 'Deep learning. Comptage personnes.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-144', brand: 'Hikvision', model: 'DS-2CD2T87G2', category: 'camera_bullet', subcategory: 'Bullet 8MP ColorVu', specs: { resolution: '8MP', fov: 102, rangeM: 12, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 40 }, price_fcfa: 580_000, price_eur: 884, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Hikvision iVMS'], installation_notes: 'ColorVu couleur nuit. Entrées.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-145', brand: 'Dahua', model: 'IPC-HFW3849T1', category: 'camera_bullet', subcategory: 'Bullet TiOC 8MP', specs: { resolution: '8MP', fov: 102, rangeM: 10, ip_rating: 'IP67', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 30 }, price_fcfa: 450_000, price_eur: 686, datasheet_url: '', certifications: ['CE', 'IP67'], compatible_with: ['Dahua DSS'], installation_notes: 'TiOC: sirène + lumière intégrée.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'Electroplanet CI' },
  { id: 'eq-146', brand: 'Bosch', model: 'FLEXIDOME corner 7100i', category: 'camera_dome', subcategory: 'Dôme angle 6MP', specs: { resolution: '6MP', fov: 183, rangeM: 6, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 15, poe: true, h265: true, wdr: true }, price_fcfa: 1_200_000, price_eur: 1829, datasheet_url: '', certifications: ['CE', 'EN 62676', 'IP66'], compatible_with: ['Bosch VMS'], installation_notes: 'Montage angle mur. Vue 183°.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-147', brand: 'Assa Abloy', model: 'CLIQ Go', category: 'electric_lock', subcategory: 'Cylindre électronique programmable', specs: { power_watts: 0, battery_hours: 30000, credential_types: ['clé programmable'] }, price_fcfa: 280_000, price_eur: 427, datasheet_url: '', certifications: ['CE', 'EN 15684'], compatible_with: ['CLIQ Web Manager'], installation_notes: 'Cylindre électronique. Rétro-fit.', maintenance_interval_months: 24, available_abidjan: false, supplier_ci: 'SecuriTech CI' },
  { id: 'eq-148', brand: 'Honeywell', model: 'ProWatch 4000', category: 'door_controller', subcategory: 'Contrôleur multi-porte enterprise', specs: { power_watts: 25, credential_types: ['badge', 'bio'] }, price_fcfa: 1_350_000, price_eur: 2058, datasheet_url: '', certifications: ['CE', 'UL'], compatible_with: ['Honeywell ProWatch'], installation_notes: 'Enterprise multi-porte. 8 lecteurs.', maintenance_interval_months: 12, available_abidjan: false, supplier_ci: 'TechnoSafe Abidjan' },
  { id: 'eq-149', brand: 'Kidde', model: 'FM200 Clean Agent', category: 'fire_alarm_panel', subcategory: 'Extinction FM200', specs: { coverage_m2: 50, response_time_sec: 10, power_watts: 0 }, price_fcfa: 8_500_000, price_eur: 12957, datasheet_url: '', certifications: ['CE', 'EN 15004', 'APSAD'], compatible_with: [], installation_notes: 'Salle serveur. Extinction propre.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-150', brand: 'Custom', model: 'Borne Info Touch 55"', category: 'digital_signage', subcategory: 'Borne info tactile 55"', specs: { screen_size_inch: 55, brightness_nits: 700, power_watts: 150, connectivity: ['WiFi', 'LAN', 'USB'] }, price_fcfa: 4_200_000, price_eur: 6403, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'Kiosk premium tactile. Hall principal.', maintenance_interval_months: 6, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-151', brand: 'Wisenet', model: 'PNV-A6081R', category: 'camera_dome', subcategory: 'Dôme AI 2MP vandal', specs: { resolution: '2MP', fov: 104, rangeM: 10, ip_rating: 'IP66', ik_rating: 'IK10', power_watts: 12, poe: true, h265: true, wdr: true, ir_range_m: 25 }, price_fcfa: 820_000, price_eur: 1250, datasheet_url: '', certifications: ['CE', 'IP66', 'IK10'], compatible_with: ['Wisenet WAVE'], installation_notes: 'AI embarquée. Vandal-proof.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SIMTEC' },
  { id: 'eq-152', brand: 'Custom', model: 'Poteau Inox QR', category: 'qr_code_stand', subcategory: 'Poteau inox porte-QR', specs: { dimensions_mm: '300x300x1100', weight_kg: 8 }, price_fcfa: 65_000, price_eur: 99, datasheet_url: '', certifications: [], compatible_with: [], installation_notes: 'Inox brossé. Entrées enseignes.', maintenance_interval_months: 24, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-153', brand: 'Custom', model: 'Panneau Parking LED', category: 'parking_guidance', subcategory: 'Panneau directeur parking', specs: { power_watts: 20, dimensions_mm: '1000x300x50' }, price_fcfa: 180_000, price_eur: 274, datasheet_url: '', certifications: ['CE'], compatible_with: [], installation_notes: 'LED. Flèches directionnelles parking.', maintenance_interval_months: 12, available_abidjan: true, supplier_ci: 'SignaPrint CI' },
  { id: 'eq-154', brand: 'Notifier', model: 'NFW2-100', category: 'fire_alarm_panel', subcategory: 'Centrale wireless', specs: { power_watts: 50, channels: 4 }, price_fcfa: 2_800_000, price_eur: 4268, datasheet_url: '', certifications: ['CE', 'EN 54-2'], compatible_with: ['Notifier wireless detectors'], installation_notes: 'Sans fil. Extension bâtiment existant.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
  { id: 'eq-155', brand: 'Hanwha', model: 'TNO-4051T', category: 'camera_bullet', subcategory: 'Bullet thermique', specs: { resolution: 'VGA', fov: 50, rangeM: 50, ip_rating: 'IP66', power_watts: 12, poe: true }, price_fcfa: 4_200_000, price_eur: 6403, datasheet_url: '', certifications: ['CE', 'IP66'], compatible_with: ['Wisenet WAVE'], installation_notes: 'Thermique. Détection incendie ext.', maintenance_interval_months: 6, available_abidjan: false, supplier_ci: 'SIMTEC' },
]

// ═══ HELPER FUNCTIONS ═══

export function getEquipmentByCategory(category: string): EquipmentItem[] {
  return EQUIPMENT_DATABASE.filter(e => e.category === category)
}

export function getEquipmentByBrand(brand: string): EquipmentItem[] {
  return EQUIPMENT_DATABASE.filter(e => e.brand.toLowerCase() === brand.toLowerCase())
}

export function getAvailableInAbidjan(): EquipmentItem[] {
  return EQUIPMENT_DATABASE.filter(e => e.available_abidjan)
}

export function searchEquipment(query: string): EquipmentItem[] {
  const q = query.toLowerCase()
  return EQUIPMENT_DATABASE.filter(e =>
    e.brand.toLowerCase().includes(q) ||
    e.model.toLowerCase().includes(q) ||
    e.subcategory.toLowerCase().includes(q) ||
    e.category.toLowerCase().includes(q)
  )
}

export function getUniqueBrands(): string[] {
  return [...new Set(EQUIPMENT_DATABASE.map(e => e.brand))].sort()
}

export function getUniqueCategories(): string[] {
  return [...new Set(EQUIPMENT_DATABASE.map(e => e.category))].sort()
}
