// ═══ PROJECT TEMPLATES — 5 Templates ═══

import type { ProjectTemplate } from './types'

export const PROJECT_TEMPLATES: ProjectTemplate[] = [
  {
    id: 'tpl-mall-standard', name: 'Mall standard UEMOA', type: 'mall',
    description: 'Centre commercial 20 000 – 40 000 m². Configuration standard avec parking souterrain, galeries commerciales et food court.',
    default_zones: [
      { label: 'Parking B1', type: 'parking', surfaceRatio: 0.25 },
      { label: 'Hall principal RDC', type: 'circulation', surfaceRatio: 0.15 },
      { label: 'Galerie commerciale RDC', type: 'commerce', surfaceRatio: 0.25 },
      { label: 'Food court RDC', type: 'restauration', surfaceRatio: 0.10 },
      { label: 'Galerie commerciale R+1', type: 'commerce', surfaceRatio: 0.15 },
      { label: 'Locaux techniques', type: 'technique', surfaceRatio: 0.05 },
      { label: 'Back-office', type: 'backoffice', surfaceRatio: 0.05 },
    ],
    default_camera_density: 0.35,
    default_door_rules: ['Badge + biométrie zones techniques', 'Badge zones backoffice', 'Libre accès zones publiques'],
    checklist_items: ['Plan DXF validé', 'Budget sécurité approuvé', 'Prestataire sécurité sélectionné', 'Équipements commandés', 'Installation vidéosurveillance', "Installation contrôle d'accès", 'Tests intégration', 'Formation agents', 'Exercice évacuation', 'Recette finale'],
    estimated_capex_per_m2_fcfa: 8500, icon: '🏬',
  },
  {
    id: 'tpl-mall-premium', name: 'Mall premium UEMOA', type: 'mall',
    description: "Centre commercial premium > 40 000 m². Haut niveau de sécurité et d'expérience client avec programme fidélité.",
    default_zones: [
      { label: 'Parking B1-B2', type: 'parking', surfaceRatio: 0.20 },
      { label: 'Hall & atrium', type: 'circulation', surfaceRatio: 0.12 },
      { label: 'Galerie standard', type: 'commerce', surfaceRatio: 0.20 },
      { label: 'Galerie premium', type: 'commerce', surfaceRatio: 0.12 },
      { label: 'Food court & terrasse', type: 'restauration', surfaceRatio: 0.12 },
      { label: 'Loisirs & cinéma', type: 'loisirs', surfaceRatio: 0.10 },
      { label: 'Services financiers', type: 'financier', surfaceRatio: 0.04 },
      { label: 'Locaux techniques', type: 'technique', surfaceRatio: 0.05 },
      { label: 'Back-office', type: 'backoffice', surfaceRatio: 0.05 },
    ],
    default_camera_density: 0.45,
    default_door_rules: ['Biométrie + SAS zones financières', 'Badge + biométrie zones techniques', 'Badge zones backoffice', 'Accès VIP Cosmos Club'],
    checklist_items: ['Plan DXF validé', 'Étude sécurité APSAD R82', 'Budget approuvé', 'App Cosmos Club développée', 'Prestataire sécurité sélectionné', 'Signalétique fabriquée', 'Équipements installés', 'Tests intégration', 'Formation SSIAP', 'Exercice évacuation', 'Signalétique installée', 'Recette générale', 'Ouverture'],
    estimated_capex_per_m2_fcfa: 12000, icon: '🏪',
  },
  {
    id: 'tpl-proximity', name: 'Centre commercial de proximité', type: 'mall',
    description: 'Centre < 10 000 m². Configuration simple avec supermarché ancre et galerie marchande.',
    default_zones: [
      { label: 'Parking extérieur', type: 'exterieur', surfaceRatio: 0.30 },
      { label: 'Hall', type: 'circulation', surfaceRatio: 0.10 },
      { label: 'Supermarché', type: 'commerce', surfaceRatio: 0.35 },
      { label: 'Galerie marchande', type: 'commerce', surfaceRatio: 0.15 },
      { label: 'Locaux techniques', type: 'technique', surfaceRatio: 0.05 },
      { label: 'Back-office', type: 'backoffice', surfaceRatio: 0.05 },
    ],
    default_camera_density: 0.25,
    default_door_rules: ['Badge zones techniques', 'Libre accès zones publiques'],
    checklist_items: ['Plan validé', 'Budget approuvé', 'Installation sécurité', 'Tests', 'Ouverture'],
    estimated_capex_per_m2_fcfa: 5500, icon: '🛒',
  },
  {
    id: 'tpl-office', name: 'Immeuble de bureaux premium', type: 'office',
    description: "Immeuble de bureaux haut standing. Contrôle d'accès renforcé, vidéosurveillance ciblée.",
    default_zones: [
      { label: 'Parking souterrain', type: 'parking', surfaceRatio: 0.20 },
      { label: 'Hall & accueil', type: 'circulation', surfaceRatio: 0.10 },
      { label: 'Bureaux', type: 'bureaux', surfaceRatio: 0.50 },
      { label: 'Salles de réunion', type: 'services', surfaceRatio: 0.05 },
      { label: 'Cafétéria', type: 'restauration', surfaceRatio: 0.05 },
      { label: 'Locaux techniques', type: 'technique', surfaceRatio: 0.05 },
      { label: 'Back-office', type: 'backoffice', surfaceRatio: 0.05 },
    ],
    default_camera_density: 0.20,
    default_door_rules: ['Badge tous les étages', 'Biométrie direction', 'Badge parking'],
    checklist_items: ['Plan validé', 'Étude sécurité', "Installation contrôle accès", 'Installation vidéo', 'Tests', 'Ouverture'],
    estimated_capex_per_m2_fcfa: 6000, icon: '🏢',
  },
  {
    id: 'tpl-hypermarket', name: 'Hypermarché avec galerie', type: 'mall',
    description: 'Hypermarché avec galerie commerciale attenante. Fort focus antivol et flux clients.',
    default_zones: [
      { label: 'Parking', type: 'exterieur', surfaceRatio: 0.25 },
      { label: 'Hypermarché', type: 'commerce', surfaceRatio: 0.40 },
      { label: 'Galerie', type: 'commerce', surfaceRatio: 0.15 },
      { label: 'Restauration', type: 'restauration', surfaceRatio: 0.08 },
      { label: 'Réserves', type: 'technique', surfaceRatio: 0.07 },
      { label: 'Back-office', type: 'backoffice', surfaceRatio: 0.05 },
    ],
    default_camera_density: 0.40,
    default_door_rules: ['Badge réserves', 'Portiques antivol sorties', 'Badge back-office'],
    checklist_items: ['Plan validé', 'Étude sécurité + antivol', 'Budget approuvé', 'Installation complète', 'Tests + calibrage antivol', 'Formation', 'Ouverture'],
    estimated_capex_per_m2_fcfa: 7500, icon: '🛍️',
  },
]
